Errors/urls.py
from django.conf.urls import patterns, url

from Errors import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    )

HereOrThere/urls.py
from django.conf.urls import patterns, include, url
import FBLogin
from django.contrib import admin
import Rankings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'HereOrThere.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('SiteUsers.urls',namespace='SiteUsers')),
    url(r'^locate/', include('Location.urls',namespace='Location')),
    url(r'^sheepoff/', include('Battles.urls',namespace='Battles')),
    url(r'^instagram/', include('Instagram.urls',namespace='Instagram')),
    url(r'^errors/', include('Errors.urls',namespace='Errors')),
    url(r'^rankings/', include('Rankings.urls',namespace='Rankings')),
)

Location/urls.py
from django.conf.urls import patterns, url

from Location import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^instructions/', views.index, name='instructions'),
)

Location/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from SiteUsers.models import UserProfile
from django.contrib.auth.models import User

@login_required
def index(request):
	if request.session['IG_authd']:
		context={'goog_key':settings.GOOG_KEY}
		return render(request,'Location/locateme.html',context)
	else:
		return HttpResponseRedirect(reverse('SiteUsers:instagram')+'?state='+'login')

def instructions(request):
	if request.session['IG_authd']:
		return render(request,'Location/instructions.html',context)
	else:
		return HttpResponseRedirect(reverse('SiteUsers:instagram')+'?state='+'login')

Location/templates/Location/instructions.html
{% extends "base.html" %}

{% block pagetitle %}
Set your location
{% endblock %}

{% block jumboheading %}
{% endblock %}


{% block content %}
Place a marker on your location. Click the marker to set your location.
<p id="purereplicaformbutton" class="pure-form pure-form-aligned" >
    <a id="purereplicaformbutton" class="pure-button pure-input-1-2 pure-button-primary active" href="{% url 'Location:index' %}">Connect to Instagram</a>
</p>




{% endblock %}

Location/templates/Location/locateme.html
{% extends "base_login.html" %}

{% block pagetitle %}
Choose Your Location
{% endblock %}

{% block style %}
html, body {
        height: 100%;
        margin: 0px;
        padding: 0px
      }

#jbtron {
  height: 500px;
}
{% endblock %}

{% block prescript %}
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key={{ goog_key }}">
</script>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script>  -->
{% endblock %}
{% block script %}
    var initialLocation;
    var siberia = new google.maps.LatLng(60, 105);
    var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
    var browserSupportFlag =  new Boolean();

    function initialize() {
      var mapOptions = {
        zoom: 12,
      }
      var map = new google.maps.Map(document.getElementById('jbtron'), mapOptions);

      var marker=new google.maps.Marker({
        position:newyork,
        map: map
      });

      function placeMarker(location) {
          if ( marker ) {
            marker.setPosition(location);
          } else {
            marker = new google.maps.Marker({
              position: location,
              map: map
            });
          }
        }

      google.maps.event.addListener(map, 'click', function(event) {
        placeMarker(event.latLng);
        });

// need to pass redirect url 

      google.maps.event.addListener(marker, 'click', 
        function() {
            var pos = marker.getPosition();
            window.location.href='{{BattleURL}}' +'?lat=' +encodeURIComponent( pos.lat() ) +'&lon=' +encodeURIComponent( pos.lng() ) ;
        });

      if(navigator.geolocation) {
        browserSupportFlag = true;
        navigator.geolocation.getCurrentPosition(function(position) {
          initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
          map.setCenter(initialLocation);
          
        }, function() {
          handleNoGeolocation(browserSupportFlag);
        });
      }
      // Browser doesn't support Geolocation
      else {
        browserSupportFlag = false;
        handleNoGeolocation(browserSupportFlag);
      }

      function handleNoGeolocation(errorFlag) {
        if (errorFlag == true) {
          alert("Geolocation service failed.");
          initialLocation = newyork;
        } else {
          alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
          initialLocation = siberia;
        }
        map.setCenter(initialLocation);
      }
    }

    google.maps.event.addDomListener(window, 'load', initialize);

{% endblock %}

{% block tester %}
<div id="map-canvas"></div>
{% endblock %}


    

Location/templates/Location/test.html
<!DOCTYPE html>
<html>
  <head>

    <style type="text/css">
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCl0lwA38Jykb_obSa822VQ17RCnQc5uG8">
    </script>
    <script type="text/javascript">
      var initialLocation;
    var siberia = new google.maps.LatLng(60, 105);
    var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
    var browserSupportFlag =  new Boolean();

    function initialize() {
    //  var myLatlng = new google.maps.LatLng(-25.363882,131.044922);
      var mapOptions = {
        zoom: 12,
    //    center: myLatlng
      }
      var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

      var marker=new google.maps.Marker({
        position:newyork,
        map: map
      });

      function placeMarker(location) {
          if ( marker ) {
            marker.setPosition(location);
          } else {
            marker = new google.maps.Marker({
              position: location,
              map: map
            });
          }
        }

      google.maps.event.addListener(map, 'click', function(event) {
        placeMarker(event.latLng);
        });

// need to pass redirect url 

      google.maps.event.addListener(marker, 'click', 
        function() {
            var pos = marker.getPosition();
            window.location.href='{{BattleURL}}' +'?lat=' +encodeURIComponent( pos.lat() ) +'&lon=' +encodeURIComponent( pos.lng() ) ;
        });

      if(navigator.geolocation) {
        browserSupportFlag = true;
        navigator.geolocation.getCurrentPosition(function(position) {
          initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
          map.setCenter(initialLocation);
          
        }, function() {
          handleNoGeolocation(browserSupportFlag);
        });
      }
      // Browser doesn't support Geolocation
      else {
        browserSupportFlag = false;
        handleNoGeolocation(browserSupportFlag);
      }

      function handleNoGeolocation(errorFlag) {
        if (errorFlag == true) {
          alert("Geolocation service failed.");
          initialLocation = newyork;
        } else {
          alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
          initialLocation = siberia;
        }
        map.setCenter(initialLocation);
      }
    }

    google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
    <div id="map-canvas"/>
  </body>
</html>