Errors/urls.py
from django.conf.urls import patterns, url

from Errors import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    )

HereOrThere/urls.py
from django.conf.urls import patterns, include, url
import FBLogin
from django.contrib import admin
import Rankings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'HereOrThere.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('SiteUsers.urls',namespace='SiteUsers')),
    url(r'^locate/', include('Location.urls',namespace='Location')),
    url(r'^sheepoff/', include('Battles.urls',namespace='Battles')),
    url(r'^instagram/', include('Instagram.urls',namespace='Instagram')),
    url(r'^errors/', include('Errors.urls',namespace='Errors')),
    url(r'^rankings/', include('Rankings.urls',namespace='Rankings')),
)

SiteUsers/urls.py
from django.conf.urls import patterns, url

from SiteUsers import views

urlpatterns = patterns('',
	url(r'^register/$', views.register, name='register'),
	url(r'^logout/$',views.logout_view, name='logout'),
	url(r'^login/$',views.login_view, name='login'),
	url(r'^instagram/$',views.instagram, name='instagram'),
)

HereOrThere/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.


def home(request):
	if 'next' in request.GET:
		next_url = request.GET['next']
	if not request.user.is_authenticated():
		# context = {'next_url':next_url}
		context = {}
		return render(request,'base_login.html',context)
	else:
		return HttpResponse('Hi')		

HereOrThere/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
<!-- Bootstrap core CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'HereOrThere/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'HereOrThere/css/pure-min.css' %}" />
	<!-- Custom styles for this template -->
	<link rel="stylesheet" type="text/css" href="{% static 'HereOrThere/css/jumbotron-narrow.css' %}" />
<title>BarBarSheep: {% block pagetitle %}{% endblock %}</title>
	<style>
    {%block style%}
    {% endblock %}
    </style>
<meta charset="UTF-8">
</head>
{% block prescript %}{% endblock %}
<script>



  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
 

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '{{FACEBOOK_APP_ID}}',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.0' // use version 2.0
  });


  FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));


  function log_user_in(response) {
    var form = document.getElementById("login_form");
    var uid = response.authResponse.userID;
    var token = response.authResponse.accessToken;
    document.getElementById('fb_userid_field').setAttribute('value',uid);
    document.getElementById('fb_token_field').setAttribute('value',token);
    form.submit()
  }

  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  function statusChangeCallback(response) {

    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      log_user_in(response);
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please authorize BarBarSheep';
    } 
  }


  function logout(event) {
    event.preventDefault();
    FB.logout(function(response) {}); 
    window.location.replace("{% url 'SiteUsers:logout' %}");
  }



{% block script %}{% endblock %}</script>
<body>

<div class="container">
      <div class="header">
<!--Login buttons or logout button-->

        {% block navright %}
          <ul class="nav nav-pills pull-right">
  {% if user.is_authenticated %}
    
      <form class="navbar-form nav-pills navbar-right" role="logout" >
      <img src="{{ user.userprofile.ig_pic }}" width=25>
      {{ user.userprofile.ig_username }}
        <button type="submit" class="btn btn-default" onClick="JavaScript:logout(event)">Logout</button>
      </form>

  {% else %}
    <form id='login_form' class="navbar-form nav-pills navbar-right" action="{% url 'SiteUsers:login' %}"role="login" method="post">
      {% csrf_token %}
      <input id='fb_userid_field' type='hidden' name='fb_user_id'  />
      <input id='fb_token_field' type='hidden' name='fb_user_token'  />
    </form>

    <fb:login-button class="navbar-form nav-pills navbar-right" size="large" scope={{FBPermissions}}
                 onlogin="checkLoginState()">
  Login via Facebook
</fb:login-button>
<li id='status' class="navbar-form nav-pills navbar-right"></li>
  {% endif %}

  </ul>

        {% endblock %}
        <h3 class="text-muted">BarBarSheep</h3>

      </div>


      <div class="center_box" id="jbtron">

        <h1>{% block jumboheading %}{% endblock %}</h1>
        <p class="lead">

{% block content %}hi{% endblock %}</p>
      </div>
{% block postjumbo %} {% endblock %}

      <div class="footer">
        <p>&copy; BarBarSheep 2014</p>
      </div>

    </div> <!-- /container -->
{% block tester %}{% endblock %}

</body>
</html>

<!DOCTYPE html>
<html lang="en">
  <head>
  

    <title>Narrow Jumbotron Template for Bootstrap</title>

    

    

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

HereOrThere/templates/base_login.html
<!-- For page where user wants to login or is logged in -->
{% extends "base.html" %}

{% block navright %}


{% endblock %}